version: "3.5"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: "frontend"
    restart: "no"
    ports:
      - "3100:3100"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: "backend"
    restart: "no"
    #env_file: .env # At somepoint we should put passwords and such in a .env file, not in the repo
    ports:
      - "3101:3101"
    volumes:
      - ./backend:/usr/src/app
